---
title: "Data Analysis 3/15"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
freq19j<-read.csv("Jan19.csv")
freq19mar<-read.csv("Mar19.csv")
freq19m<-read.csv("May19.csv")
freq19jul<-read.csv("Jul19.csv")
```


```{r}
freq19<-read.csv("freq_2019.csv")
```


```{r}
par(mfrow=c(2,2))
hist(freq19j$f,breaks=100,prob=TRUE)
hist(freq19mar$f,breaks=100,prob=TRUE)
hist(freq19m$f,breaks=100,prob=TRUE)
hist(freq19jul$f,breaks=100,prob=TRUE)
abline(v=50.015)
abline(v=49.985)
```

Still bimodal. This is only for January and May 2019. Can see temporal shifting of peaks through the year. Governor deadband plotted as vertical lines in July plot.

```{r}
r=48*365
plot(c(1:r),demand$ND)
```


```{r}
mean(freq19j$f)
mean(freq19mar$f)
mean(freq19m$f)
mean(freq19jul$f)
```

```{r}
#Finding Standard deviation for 2 minutes around the market jumps every 4th trading interval (every 2 hours)
intlength=30*60*4
len=length(freq19j[,1])/intlength
for(i in 1:len){
  low=intlength*i
  high=intlength*i+6
  freq19j$jump_std[i]=sd(freq19j$f[low:high])
}
```

```{r}
par(mfrow=c(2,2))
plot((1/12)*c(1:108),freq19j$jump_std[1:108],type="l")
plot((1/12)*c(1:108),freq19mar$jump_std[1:108],type="l")
plot((1/12)*c(1:108),freq19m$jump_std[1:108],type="l")
plot((1/12)*c(1:108),freq19jul$jump_std[1:108],type="l")
```
Once again we see periodic behavior with spikes at midnight. When interval is widened, this periodicity weakens.

```{r}
plot(c(1750:1850),freq19j$f[1750:1850],type="l")
plot(c(3580:3620),freq19j$f[3580:3620],type="l")
```
```{r}
freq19jul$over50<-ifelse(freq19jul$f>50,1,0)
```


```{r}
#Finding proportion of jump interval above 50 for each market interval jump every 2 hours
intlength=30*60*4
len=length(freq19jul$f)/intlength
for(i in 1:len){
  low=intlength*i
  high=intlength*i+6
  freq19jul$jump_over50[i]=mean(freq19jul$over50[low:high])
}
```

```{r}
mean(freq19j$jump_over50[1:len-1])
mean(freq19mar$jump_over50[1:len-1])
mean(freq19m$jump_over50[1:len-1])
mean(freq19jul$jump_over50[1:len-1])
```

```{r}
hist(freq19j$jump_over50[1:len-1])
hist(freq19mar$jump_over50[1:len-1])
hist(freq19m$jump_over50[1:len-1])
hist(freq19jul$jump_over50[1:len-1])
```
```{r}
#Finding proportion of frequency above 50 for each market interval
intlength=30*60
len=length(freq19m$f)/intlength
for(i in 0:1799){
  low=intlength*i+1
  high=intlength*i+intlength
  freq19m$period_over50[i+1]=mean(freq19m$over50[low:high])
}
```

```{r}
len=length(freq19j$f)
mean(freq19j$over50[1:len-1])
mean(freq19mar$over50[1:len-1])
mean(freq19m$over50[1:len-1])
mean(freq19jul$over50[1:len-1])
```

```{r}
write.csv(freq19j,"Jan.csv")
write.csv(freq19mar,"Mar.csv")
write.csv(freq19m,"May.csv")
write.csv(freq19jul,"Jul.csv")
```

```{r}
len=length(freq19m$f)/1800
mean(freq19j$jump_over50[1:len-1])
mean(freq19mar$jump_over50[1:len-1])
mean(freq19m$jump_over50[1:len-1])
mean(freq19jul$jump_over50[1:len-1])
```

```{r}
l=length(freq19j$f)/(1800*4)-1
mean(freq19j$jump_std[1:l])
mean(freq19mar$jump_std[1:l])
mean(freq19m$jump_std[1:l])
mean(freq19jul$jump_std[1:l])
```

```{r}
l=length(freq19j$f)/(1800*4)-1
t.test(freq19jul$jump_std[1:l], y = freq19j$jump_std[1:l], alternative = c("two.sided", "less", "greater"), mu = 0, 
        paired = FALSE, var.equal = FALSE, conf.level = 0.95)
```

```{r}
demand<-read.csv("Demand_2019.csv")
```

```{r}
acf(freq19j$f,lag.max=10000)
```

```{r}
hist(freq19j$over50)
```

```{r}

```

